import logging
from datetime import datetime

import discord
import pytz

logger = logging.getLogger(__name__)

KST = pytz.timezone("Asia/Seoul")

CATEGORY_EMOJIS = {
    "속보": "🚨",
    "이적": "🔄",
    "경기": "⚽",
    "일반": "ℹ️",
}


async def send_as_embeds(
    channel,
    articles: list[dict],
    match_analysis: dict | None = None,
    *,
    fallback_mode: bool = False,
):
    today_kst = datetime.now(KST).strftime('%Y년 %m월 %d일')

    logger.info("Discord Embed 전송 시작 (기사 %d건)", len(articles))

    if not articles:
        await channel.send("❌ 표시할 뉴스가 없습니다.")
        return

    if match_analysis:
        embed = discord.Embed(
            description=match_analysis["text"],
            color=match_analysis["color"],
            timestamp=datetime.now(KST),
        )
        embed.set_author(name="⚽ 경기 분석")
        embed.set_footer(text="AI Generated by DeepSeek")
        await channel.send(embed=embed)

    if fallback_mode:
        await channel.send(
            f"⚠️ **[{today_kst}]** AI 요약에 실패하여 **원문 링크 목록**을 전송합니다.\n"
            "아래 링크에서 직접 기사를 확인해 주세요."
        )
    else:
        header = f"📢 **[{today_kst}] AI 분석: 오늘의 맨유 전문 브리핑 (고도화 버전)**\n\n"
        await channel.send(header)

    for article in articles:
        emoji = CATEGORY_EMOJIS.get(article["category"], "ℹ️")
        is_tier1 = "⭐" in article["tier"]
        embed_color = 0xFFD700 if is_tier1 else article["color"]

        embed = discord.Embed(
            title=article["title"],
            url=article.get("link"),
            description=article["summary"],
            color=embed_color,
            timestamp=datetime.now(KST),
        )
        embed.set_author(name=f"{emoji} {article['category']}")
        embed.add_field(name="언론사", value=article["source"], inline=True)
        embed.add_field(name="공신력", value=article["tier"], inline=True)
        embed.set_footer(text=f"발행일: {article['date']}")

        await channel.send(embed=embed)

    logger.info("Embed 전송 완료")
