import asyncio
import logging
from datetime import datetime

import discord
import pytz

from config import EMBED_SEND_DELAY_SEC, MAX_EMBEDS_PER_RUN

logger = logging.getLogger(__name__)

KST = pytz.timezone("Asia/Seoul")

EMBED_TITLE_LIMIT = 256
EMBED_DESC_LIMIT = 4096
EMBED_FIELD_LIMIT = 1024

CATEGORY_EMOJIS = {
    "속보": "🚨",
    "이적": "🔄",
    "경기": "⚽",
    "일반": "ℹ️",
}


def truncate(text: str, limit: int, suffix: str = "…") -> str:
    text = text or ""
    if len(text) <= limit:
        return text
    if limit <= len(suffix):
        return text[:limit]
    return text[: limit - len(suffix)] + suffix


def split_embed_description(text: str, limit: int = EMBED_DESC_LIMIT) -> list[str]:
    if len(text) <= limit:
        return [text]
    chunks = []
    remaining = text
    while remaining:
        if len(remaining) <= limit:
            chunks.append(remaining)
            break
        split_at = remaining.rfind("\n", 0, limit)
        if split_at <= 0:
            split_at = limit
        chunks.append(remaining[:split_at])
        remaining = remaining[split_at:].lstrip("\n")
    return chunks


def prioritize_articles(articles: list[dict], max_count: int | None = None) -> list[dict]:
    limit = max_count if max_count is not None else MAX_EMBEDS_PER_RUN
    if limit <= 0 or len(articles) <= limit:
        return articles
    tier1 = [a for a in articles if "⭐" in a.get("tier", "")]
    rest = [a for a in articles if "⭐" not in a.get("tier", "")]
    selected = (tier1 + rest)[:limit]
    logger.info("Embed 상한 적용: %d건 → %d건 (1티어 우선)", len(articles), len(selected))
    return selected


def prepare_article_embed(article: dict) -> discord.Embed:
    emoji = CATEGORY_EMOJIS.get(article["category"], "ℹ️")
    is_tier1 = "⭐" in article["tier"]
    embed_color = 0xFFD700 if is_tier1 else article["color"]

    embed = discord.Embed(
        title=truncate(article["title"], EMBED_TITLE_LIMIT),
        url=article.get("link") or None,
        description=truncate(article["summary"], EMBED_DESC_LIMIT),
        color=embed_color,
        timestamp=datetime.now(KST),
    )
    embed.set_author(name=truncate(f"{emoji} {article['category']}", EMBED_TITLE_LIMIT))
    embed.add_field(
        name="언론사",
        value=truncate(article["source"], EMBED_FIELD_LIMIT),
        inline=True,
    )
    embed.add_field(
        name="공신력",
        value=truncate(article["tier"], EMBED_FIELD_LIMIT),
        inline=True,
    )
    embed.set_footer(text=truncate(f"발행일: {article['date']}", EMBED_FIELD_LIMIT))
    return embed


async def _send_with_delay(target, *, embed=None, content=None, delay: float = EMBED_SEND_DELAY_SEC):
    if embed is not None:
        await target.send(embed=embed)
    elif content is not None:
        await target.send(content=content)
    if delay > 0:
        await asyncio.sleep(delay)


async def _send_match_analysis(target, match_analysis: dict) -> None:
    chunks = split_embed_description(match_analysis["text"])
    for i, chunk in enumerate(chunks):
        embed = discord.Embed(
            description=chunk,
            color=match_analysis["color"],
            timestamp=datetime.now(KST),
        )
        title = "⚽ 경기 분석" if i == 0 else f"⚽ 경기 분석 ({i + 1}/{len(chunks)})"
        embed.set_author(name=title)
        embed.set_footer(text="AI Generated by DeepSeek")
        await _send_with_delay(target, embed=embed)


async def send_as_embeds(
    target,
    articles: list[dict],
    match_analysis: dict | None = None,
    *,
    fallback_mode: bool = False,
) -> list[str]:
    """Embed를 전송하고 실제로 보낸 기사 URL 목록을 반환합니다."""
    today_kst = datetime.now(KST).strftime("%Y년 %m월 %d일")
    articles = prioritize_articles(articles)

    logger.info("Discord Embed 전송 시작 (기사 %d건)", len(articles))
    sent_urls: list[str] = []

    if not articles and not match_analysis:
        await target.send("❌ 표시할 뉴스가 없습니다.")
        return sent_urls

    if match_analysis:
        await _send_match_analysis(target, match_analysis)

    if articles:
        if fallback_mode:
            await _send_with_delay(
                target,
                content=(
                    f"⚠️ **[{today_kst}]** AI 요약에 실패하여 **원문 링크 목록**을 전송합니다.\n"
                    "아래 링크에서 직접 기사를 확인해 주세요."
                ),
            )
        else:
            header = f"📢 **[{today_kst}] AI 분석: 오늘의 맨유 전문 브리핑 (고도화 버전)**\n\n"
            await _send_with_delay(target, content=header)

        for article in articles:
            embed = prepare_article_embed(article)
            await _send_with_delay(target, embed=embed)
            link = article.get("link")
            if link:
                sent_urls.append(link)

    logger.info("Embed 전송 완료 (%d건)", len(sent_urls))
    return sent_urls
